[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22.12.0"
  NPM_CONFIG_BUILD_FROM_SOURCE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
