[phases.setup]
nixPkgs = ['nodejs_22', 'python3', 'gcc']

[phases.install]
cmds = [
  'rm -rf node_modules',
  'npm install --legacy-peer-deps --force'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node .output/server/index.mjs'
