[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = [
  'npm install --include=optional --legacy-peer-deps'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node .output/server/index.mjs'
